version: "3.3"

services:
  webserver:
    container_name: woocommerce
    image: shipbeat/woocommerce
    links:
      - dbserver:mysql
    ports:
      - 8082:80
    environment:
        WORDPRESS_DB_PASSWORD: vL$j!Hbp165DMJTx3G

  dbserver:
    container_name: woo_mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: vL$j!Hbp165DMJTx3G
    ports:
      - 3307:3306
